name: Maven Build, Test, and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'  
          distribution: 'adopt'  
      
      - name: Build with Maven
        run: mvn clean install

      # - name: Send build completion alert to Microsoft Teams
      #   env:
      #     TEAMS_WEBHOOK: ${{ secrets.TEAMS_WEBHOOK }}
      #   run: |
      #     curl -X POST -H 'Content-Type: application/json' -d '{
      #       "text": "Build is complete!"
      #     }' $TEAMS_WEBHOOK
       

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'  
          distribution: 'adopt'  
      - name: Run Tests with Maven
        run: mvn test
        
      # - name: Send Alert to Teams
      #   uses: thechetantalwar/teams-notify@v2
      #   with:
      #     url: ${{ secrets.TEAMS_WEBHOOK }}
      #     payload: '{"text": "Alert! Something important happened in the repository."}' 
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build, test]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'  
          distribution: 'adopt'  

      # - name: Send deployment alert to Microsoft Teams
      #   env:
      #     TEAMS_WEBHOOK: ${{ secrets.TEAMS_WEBHOOK }}
      #   run: |
      #     curl -X POST -H 'Content-Type: application/json' -d '{
      #       "text": "Deployment to production is complete!",
      #       "event": "deployment"
      #     }' $TEAMS_WEBHOOK   

name: Send Deployment Status to Teams

on:
  deployment_status:
    types:
      - success
      - failure

jobs:
  send-teams-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare JSON Payload
        id: prepare-payload
        run: |
          status="$GITHUB_DEPLOYMENT_STATUS"
          if [ "$status" == "success" ]; then
            color="#2ECC71"  # Green
            text="Deployment was successful."
          else
            color="#D32F2F"  # Red
            text="Deployment failed."
          fi
          
          payload="{
            \"@type\": \"MessageCard\",
            \"@context\": \"http://schema.org/extensions\",
            \"themeColor\": \"$color\",
            \"summary\": \"Deployment Status\",
            \"sections\": [
              {
                \"activityTitle\": \"$text\",
                \"activityImage\": \"https://github.com/github.png\",
                \"facts\": [
                  {
                    \"name\": \"Repository\",
                    \"value\": \"$GITHUB_REPOSITORY\"
                  },
                  {
                    \"name\": \"Environment\",
                    \"value\": \"$GITHUB_ENVIRONMENT\"
                  },
                  {
                    \"name\": \"Deployed By\",
                    \"value\": \"$GITHUB_ACTOR\"
                  }
                ]
              }
            ]
          }"
          
          echo "$payload" > payload.json
          
          echo "::set-output name=payload::$(cat payload.json)"
          
        env:
          GITHUB_DEPLOYMENT_STATUS: ${{ github.event.deployment_status.state }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_ENVIRONMENT: ${{ github.event.deployment.environment }}
          GITHUB_ACTOR: ${{ github.actor }}

      - name: Send Notification to Teams
        run: |
          curl -X POST -H "Content-Type: application/json" -d "$(<payload.json)" ${{ secrets.MSTEAMS_WEBHOOK_URL }}
        env:
          MSTEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK }}

