name: Maven Build, Test, and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'  
          distribution: 'adopt'  
      
      - name: Build with Maven
        run: mvn clean install

      - name: Send build completion alert to Microsoft Teams
        env:
          TEAMS_WEBHOOK: ${{ secrets.TEAMS_WEBHOOK }}
        run: |
          curl -X POST -H 'Content-Type: application/json' -d '{
            "text": "Build is complete!"
          }' $TEAMS_WEBHOOK
       

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'  
          distribution: 'adopt'  
      - name: Run Tests with Maven
        run: mvn test
        
      - name: Send Alert to Teams
        uses: slack/webhook-action@v1
        with:
          url: ${{ secrets.TEAMS_WEBHOOK }}
          payload: '{"text": "Alert! Something important happened in the repository."}' 
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build, test]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'  
          distribution: 'adopt'  

      - name: Send deployment alert to Microsoft Teams
        env:
          TEAMS_WEBHOOK: ${{ secrets.TEAMS_WEBHOOK }}
        run: |
          curl -X POST -H 'Content-Type: application/json' -d '{
            "text": "Deployment to production is complete!",
            "event": "deployment"
          }' $TEAMS_WEBHOOK   
