on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: List files in workspace
        run: |
          ls -R $GITHUB_WORKSPACE
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: action-zip
        uses: montudor/action-zip@v1.0.0
